### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by deratokati88** [deratokati88/furima-32475#12]
# 自身のフリマアプリのURL
https://furima-32475.herokuapp.com/

# Basic認証のIDとパスワード
ID:admin
パスワード:2222

# 出品者用のメールアドレスとパスワード
メールアドレス:aaa@aaa
パスワード:aaa111

# 出品者以外のメールアドレスとパスワード
メールアドレス:iii@iii
パスワード:iii222

# 購入用カードの番号・期限・セキュリティコード
カード番号:4242424242424242
期限:03/24
セキュリティコード:123

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/102580939-ec1e7c80-4142-11eb-8418-5d26052277c7.png)
